### ISSUE TITLE
Multiple Channel in integration does not work

### ISSUE THREAD

**Issue by cob94440** [fwestenberg/reolink_dev#89] opened 2020-12-09 23:04 UTC
I updated last version via hacs.
I added my nvr channel 0 and it works 
but when i add other channels cameras don't appear.
What am i doing wrong

**Comment by badabing2005** [comment] 2020-12-10 00:30
Same here, 
When you add the camera, it automatically names it the name of the NVR, does not give you the option to set the name during addition
I set the options and chose the channel (from the integrations page)
Then I renamed the nvr to frontdoor (from the integrations page)
The device is still seen as nvr (my nvr name, I know very creative; ) and all the entities remained as the original entity names, ie all nvr_<action>
So I renamed all 6 of them to frontdoor
Next I added another Reolink integration, of course it is the same nvr but different channel
I chose the channel
I renamed to driveway
again, the device remained as nvr
when I started renaming the entities, it renamed the frontdoor entities
It looks like even though there are now two devices added, both are named the same, and editing one is effecting the other, there are only 6 entities, and not 6 entities per added integration
And same for device, there is one and only 1 device.

So at this stage, all we can use is a single channel.

Thanks

**Comment by badabing2005** [comment] 2020-12-10 00:40
Some screenshots to illustrate
![image](https://user-images.githubusercontent.com/22603312/101705926-12af2a00-3a56-11eb-89e8-9f248813cc9e.png)
![image](https://user-images.githubusercontent.com/22603312/101705940-18a50b00-3a56-11eb-915c-443e8bc143ce.png)
![image](https://user-images.githubusercontent.com/22603312/101705946-1c389200-3a56-11eb-9fa2-85bb4d167e4d.png)
![image](https://user-images.githubusercontent.com/22603312/101705967-25296380-3a56-11eb-90f2-a8300a351729.png)
![image](https://user-images.githubusercontent.com/22603312/101705982-2d819e80-3a56-11eb-937f-32b97ba7f5f1.png)
![image](https://user-images.githubusercontent.com/22603312/101706022-42f6c880-3a56-11eb-9c7d-8e8f46aa5b49.png)
![image](https://user-images.githubusercontent.com/22603312/101706053-50ac4e00-3a56-11eb-8eab-0520998f24cf.png)
![image](https://user-images.githubusercontent.com/22603312/101706064-55710200-3a56-11eb-875e-1d27b0fe916c.png)

**Comment by fwestenberg** [comment] 2020-12-10 07:55
The problem is: I don't own a NVR, so developing this is not easy to me. The best option would be (I think) to find a way to recognize NVR and  then add all channels at once or something. Also, it could be build more efficiënt, because all camera's now have it's own update coördinator. But for NVR I think we could work with one shared update coördinator.

**Comment by fwestenberg** [comment] 2020-12-10 08:43
Can you install Postman, and import the collection below (remove the .txt extension)? There is a Login call, insert your password in the body first. It will return a token (response field "name"). Use that in the request URL of the "Reolink API" call.

Please post the response body here. I already have some idea how to fix this... Thanks!

[Reolink API.json.txt](https://github.com/fwestenberg/reolink_dev/files/5671365/Reolink.API.json.txt)

**Comment by badabing2005** [comment] 2020-12-10 12:42
Sure, thanks for all your contributions.
See attached, and let me know if you need anything more.
BB


[nvr_response.json.txt](https://github.com/fwestenberg/reolink_dev/files/5672742/nvr_response.json.txt)

**Comment by fwestenberg** [comment] 2020-12-10 13:53
Thanks! Some things about the NVR:

I see the NVR gives an error for the infrared lights query (below), what kind of camera's do you use?

```
{
        "cmd": "GetIrLights",
        "code": 1,
        "error": {
            "detail": "ability error",
            "rspCode": -26
        }
    }
```

Next, the NVR is easy to distinguish by available channels (channelNum) and type:
```
{
        "cmd": "GetDevInfo",
        "code": 0,
        "value": {
            "DevInfo": {
                "B485": 1,
                "IOInputNum": 0,
                "IOOutputNum": 0,
                "audioNum": 16,
                "buildDay": "build 2009281",
                "cfgVer": "v2.0.0.0",
                "channelNum": 8,
                "detail": "REDACTED",
                "diskNum": 1,
                "firmVer": "v2.0.0.271_20092801",
                "hardVer": "H3MB16",
                "model": "RLN8-410-E",
                "name": "NVR",
                "serial": "REDACTED",
                "type": "NVR",
                "wifi": 0
            }
        }
 }
```

Any chance you can help me with debugging in chrome to check: 
- How to detect the active channels?
- What service is called when switching IR lights on/off

Thanks!

**Comment by badabing2005** [comment] 2020-12-10 15:16
Yeah, somehow NVR does not reponsd to getIrLights
But IR is provided by this GetIsp
`{
        "cmd": "GetIsp",
        "code": 0,
        "initial": {
            "Isp": {
                "antiFlicker": "Off",
                "backLight": "Off",
                "blc": 128,
                "blueGain": 128,
                "channel": 0,
                "dayNight": "Auto",
                "drc": 128,
                "exposure": "Auto",
                "gain": {
                    "max": 62,
                    "min": 1
                },
                "mirroring": 0,
                "nr3d": 1,
                "redGain": 128,
                "rotation": 0,
                "shutter": {
                    "max": 125,
                    "min": 0
                },
                "whiteBalance": "Auto"
            }
        },`
I made a fix in the previous version here
https://github.com/fwestenberg/reolink/pull/77

Let me know what you need with Chrome

**Comment by badabing2005** [comment] 2020-12-10 15:17
There are 3 values for ISP
- Color (IR off)
- Black (IR on)
- Auto (IR Auto depending on light level)

**Comment by badabing2005** [comment] 2020-12-10 15:24
> Any chance you can help me with debugging in chrome to check:
    How to detect the active channels?

I have them all active, I suppose I need to deactivate some and then look for what?

**Comment by fwestenberg** [comment] 2020-12-10 15:26
Well, my camera's use ISP for black/white/auto, not for the IR lights. But this service is already implemented! Check for the service: reolink. 
<img src="https://user-images.githubusercontent.com/47930023/101791719-24e7a180-3b04-11eb-91a4-03c7850b6489.png" width="500"/>

**Comment by fwestenberg** [comment] 2020-12-10 15:28
> > Any chance you can help me with debugging in chrome to check:
> > How to detect the active channels?
> 
> I have them all active, I suppose I need to deactivate some and then look for what?

You use 8 camera's? Nice! Well I also don't know what to look for. But you can see the calls to the cgi api, and somehow figure out how to detect if the camera is not active...

**Comment by badabing2005** [comment] 2020-12-10 17:56
Excellent, That service call worked for me. Thanks
So what exactly is the difference between ISP and IRLights?

As for camera being active / inactive
I think this `GetChannelstatus` should do it
Channel 7 is not active

```
   {
      "cmd" : "GetChannelstatus",
      "code" : 0,
      "value" : {
         "count" : 8,
         "status" : [
            {
               "channel" : 0,
               "online" : 1
            },
            {
               "channel" : 1,
               "online" : 1
            },
            {
               "channel" : 2,
               "online" : 1
            },
            {
               "channel" : 3,
               "online" : 1
            },
            {
               "channel" : 4,
               "online" : 1
            },
            {
               "channel" : 5,
               "online" : 1
            },
            {
               "channel" : 6,
               "online" : 1
            },
            {
               "channel" : 7,
               "online" : 0
            }
         ]
      }
```

**Comment by badabing2005** [comment] 2020-12-10 18:07
And if you want to get the camera names
cmd `GetOsd` would do that

```
        "value": {
            "Osd": {
                "bgcolor": 0,
                "channel": 1,
                "osdChannel": {
                    "enable": 1,
                    "name": "Front Door",
                    "pos": "Upper Left"
                },
                "osdTime": {
                    "enable": 1,
                    "pos": "Lower Right"
                },
                "watermark": 0
            }
        }
```

**Comment by cob94440** [comment] 2020-12-12 12:37
Do you succed in implémenting multiple camera?

**Comment by sthorley** [comment] 2020-12-14 02:18
I'd really like to see multiple stream support added back. 

It seems like a relatively minor issue that's popped up with the new UI configuration vs the old YAML configuration. The core functionality in the code still exists as we are able to select different channels in the UI setup and show the different NVR channels but only 1 at a time. The only issue is there is only the ability to configure a single channel in the UI. 

Could this be updated to allow the selection/connection to multiple channels? It seems the entities getting mixed up is only a result attempting to add the integration more than once to try and configure the extra channels (from the same NVR device).

If there was the ability to request more than 1 channel in the UI then the integration would only be needed once.

I'm happy to help with testing (on RLN410-8) if it helps.

**Comment by kaaspad** [comment] 2020-12-14 13:00
> I'd really like to see multiple channel NVR support added back.
> 
> It seems like a relatively minor issue that's popped up with the new UI configuration vs the old YAML configuration. The core functionality in the code still exists as we are able to select different channels in the UI setup and show the different NVR channels but only 1 at a time. The only issue is there is only the ability to configure a single channel in the UI.
> 
> Could this be updated to allow the selection/connection to multiple channels? The entities getting mixed up is only a result of attempting to add the integration more than once to try and configure the extra channels (from the same NVR device).
> 
> If there was the ability to request more than 1 channel in the UI then the integration would only be needed once.
> 
> I'm happy to help with testing (on RLN410-8) if it helps.
> 
> Alternatively if this cannot be easily resolved would it be possible to restore the ability to configure with YAML in the next release as people with multi channel NVR setups worked fine with the v0.7 YAML reolink_dev configuration.

I second this - I'm also happy to participate in testing of what is needed, or even allow screen share if that will help - everything worked fine before the integration with YAML. Let me know what's needed

**Comment by fwestenberg** [comment] 2020-12-14 13:47
Hi guys, I made a lot of fixes in [this](https://github.com/fwestenberg/reolink_dev/tree/NVR_and_bug_fixes) branch, you can download it as zip and overwrite all files in your custom_components/reolink_dev you can test it. Also the Options are fixed here, and I add the timeout setting. This one is not working yet, a fix in the python library is needed first. Please let me know the results. I know some small bugs are there:

- When adding the same camera again an error occurs
- Camera name for NVR gets the suffix _1 for stream 1 etc. This well be fixed later.

**Comment by fwestenberg** [comment] 2020-12-14 14:39
@badabing2005 Can you please check, probably at the place in the WebUI where you can rename your camera's what service is called to get/set the name? I prefer not to use the OSD service for this purpose. Thanks!

**Comment by badabing2005** [comment] 2020-12-14 21:21
@fwestenberg 
Many thanks for working on getting the NVR fixed,
I encountered an error

Before replacing the component, I removed the integration
Then replaced the component, and restart HASS
Added the integration,
The first screen for credentials / port went ok, I was prompted with this
![image](https://user-images.githubusercontent.com/22603312/102136909-077a4680-3e28-11eb-950d-ad80e2274ac4.png)
Not knowing what I should choose, and thinking that it will prompt me for each channel it detects, I clicked on submit, and was greeted with this error
![image](https://user-images.githubusercontent.com/22603312/102137009-2bd62300-3e28-11eb-98d2-776f7f3615ea.png)

HASS Logs:
```
2020-12-14 16:15:30 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_protocol.py", line 422, in _handle_request
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_app.py", line 499, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.8/site-packages/aiohttp/web_middlewares.py", line 118, in impl
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 18, in request_context_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 72, in ban_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 127, in auth_middleware
    return await handler(request)
  File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 129, in handle
    result = await result
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 169, in post
    return await super().post(request, flow_id)
  File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 60, in wrapper
    result = await method(view, request, *args, **kwargs)
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 106, in post
    result = await self._flow_mgr.async_configure(flow_id, data)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 155, in async_configure
    result = await self._async_handle_step(flow, cur_step["step_id"], user_input)
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 213, in _async_handle_step
    result: Dict = await getattr(flow, method)(user_input)
TypeError: async_step_nvr() missing 1 required positional argument: 'mac_address'
```

As for
{quote}
Can you please check, probably at the place in the WebUI where you can rename your camera's what service is called to get/set the name? I prefer not to use the OSD service for this purpose. 
{quote}

Unfortunately it calls SetOsd
![image](https://user-images.githubusercontent.com/22603312/102137122-532cf000-3e28-11eb-8984-5f67db41ca93.png)

Perhaps for NVR, you'd use that service to set the name.

**Comment by fwestenberg** [comment] 2020-12-14 21:50
Hi @badabing2005,

This is the stupid default screen for an INT with value between 1 and 8. Here you should select the channel you want to add. I will fix this error, but I can't really test it myself. I'm thinking about a better solution for channel selection.

**Comment by fwestenberg** [comment] 2020-12-14 22:14
Can you please update the content of config_flow.py with the latest changes? Channel selection and exception handling for existing camera should be fixed now.

**Comment by sthorley** [comment] 2020-12-14 22:24
Working!!! You're a legend.

There's some minor improvements that would be nice like allowing a name to be set for the entities when adding (currently it does NVRname1, NVRname2, NVRname3 etc. There's also a 16 channel model so it might be worth allowing the channel selection to go up to 16.

**Comment by fwestenberg** [comment] 2020-12-14 22:35
The naming of the entities will in the near future be based on the camera names on your device. So this should solve your first item.

Channel selection is already based on available number of channels. For any device with more than 1 channel you'll see the channel screen in the config flow, with max set to the number of available channels. 

Thanks a lot for the offer to test on your system! I think it could come in use some day. I live in the Netherlands, so I don't think I'm able to work for 8 more hours on this. ;)

**Comment by badabing2005** [comment] 2020-12-14 22:41
Thanks again @fwestenberg for  all the effort and time you put into this.
I must be doing something wrong or understanding it wrong.

No errors this time, 
When I added the integration, it came up with this dialog
![image](https://user-images.githubusercontent.com/22603312/102144244-27fbce00-3e33-11eb-9904-4eba72ae4046.png)

Wasn't sure if I needed to set to 1 or 8, so I tried the default value and it added a single camera (1 device 6 entities)
I deleted it and added again, this time selecting 8 (the max)
And again all I got is a 1 device 6 entities
What am I missing?
Am I supposed to add this camera 8 times? each time selecting a different channel?
I thought it would add all the channels automatically.

Let me know if I'm doing something wrong.
Thanks

BB

**Comment by sthorley** [comment] 2020-12-14 22:44
@fwestenberg that all sounds great. Late night Australia= Lunchtime in Netherlands so I can make that work if needed.

@badabing2005 You need to add the integration once per channel on you NVR selecting the appropriate channel each time. If you have old YAML config add 1 to the number of each channel as it used to start at 0 but now starts at 1 (which is same as the reolink software).

**Comment by fwestenberg** [comment] 2020-12-14 22:55
@sthorley, thanks for answering. You was just slightly faster! But this is indeed how it works now. 
The channel should be fixed and selected when adding the camera, because unique id (and some other stuff) depend on this value. So it can't be changed afterwards anymore. (Just delete the cam and start over). 

Probably in the future I will add something like:

--------------------------
Select channels to add
--------------------------
- [X]  Channel 1: Frontdoor
- [ ]  Channel 2: Garden
- [ ]  Channel 3: Pool
- [ ]  Channel 4: Bedroom
--------------------------

**Comment by sthorley** [comment] 2020-12-14 23:00
@fwestenberg that UI would be perfect. You could probably promote full NVR support at that point. The previous YAML solution was rock solid for months and if you don't need to manually define the switches and channels in YAML it should be dead simple to setup.

**Comment by fwestenberg** [comment] 2020-12-14 23:12
Could you try to update all the files to the version like in [this](https://github.com/fwestenberg/reolink_dev/tree/NVR_and_bug_fixes) branch? We need to be sure it is not working with the NVR...

**Comment by sthorley** [comment] 2020-12-14 23:22
> 
> 
> Could you try to update all the files to the version like in [this](https://github.com/fwestenberg/reolink_dev/tree/NVR_and_bug_fixes) branch? We need to be sure it is not working with the NVR...

To clarify I've overwritten the files within the reolink_dev folder with the files in the reolink_dev folder from this branch. I don't think there were changes since I did it around an hour ago but I did it again to be sure.

Motion detection still does not appear to work. Sorry

**Comment by badabing2005** [comment] 2020-12-14 23:27
Thank you @sthorley and @fwestenberg ,
I was wrongly thinking that it would add all the cameras in one shot as it detected NVR instead of a single camera.
I'll happily take whatever there is :)
But as @fwestenberg suggested, that interface would be awesome, along with all the entities being named the camera name?
I know currently rename is not working, but how would it behave once it works, if someone renames a camera, would all 6 entities take the name?
For example, if I rename `nvr1` to `frontdoor`, would entity `switch.nvr1_email` also be renamed to `switch.frontdoor_email` ?
That would be perfect.

Let me test if motion detection is working for me, I'll get back to you

**Comment by badabing2005** [comment] 2020-12-14 23:36
Yeah, motion detection is not working, it probably is picking up some other reading.
In my case it is constantly reporting Detected.
![image](https://user-images.githubusercontent.com/22603312/102148688-e838e480-3e3a-11eb-8653-10578fc458f6.png)


One other thing I noticed is that all the switches have the switch icons (except for the motion)
Even though the entities have different icons for each, they all show up as switch, even if I don't choose the default and set my own value.
The only way I get it to display a different icon is by using customization.
not sure if this is only at my end or for everyone else.

If they all show up as switch, I would need to hover on each to know which one I'm switching, visual queue (icon) helps

**Comment by sthorley** [comment] 2020-12-14 23:45
I'll just add that I went back through my logbook and motion detection was definitely working using v0.7 YAML so this is a new issue :(
Also the IR lights switch is not implemented.

That said I'm perfectly happy with this for my use case, I just wanted to get the video feeds back onto my lovelace dashboard.

**Comment by fwestenberg** [comment] 2020-12-14 23:48
I think I don't get the idea. I see it like this:

![image](https://user-images.githubusercontent.com/47930023/102149348-82665000-3e6e-11eb-99a9-3b0499d9e5f4.png)

And yes, before motion detection worked but was slow and unreliable (pulling every x seconds). The IR lights is some strange thing on the NVR. You should instead just call the service: reolink_dev.set_daynight. Before it all got mixed up, now it's like it should be. Just check the readme.

**Comment by sthorley** [comment] 2020-12-14 23:54
![image](https://user-images.githubusercontent.com/6040168/102149796-64770a80-3ec3-11eb-95de-2c4a1419d6ec.png)
![image](https://user-images.githubusercontent.com/6040168/102150036-dbac9e80-3ec3-11eb-8bf8-ddbc405d532e.png)

@fwestenberg I don't understand @badabing2005 issue either. The entities are switches so they can toggle these settings and they have appropriate icons.  The icons show in both lovelace and entity view. This is correct.

**Comment by badabing2005** [comment] 2020-12-15 00:38
Here guys,
I have frontdoor customized
```switch.frontdoor_email:
  icon: mdi:email

switch.frontdoor_ftp:
  icon: mdi:folder-remove

switch.frontdoor_record_audio:
  icon: mdi:volume-high

switch.frontdoor_recording:
  icon: mdi:filmstrip
```

I just added another channel (8)
see how frontdoor shows up and how channel 8 shows up
This should clear it up, but from the sound of it, it's only me seeing it that way.
I wonder what could it be.

![image](https://user-images.githubusercontent.com/22603312/102152851-e889ad80-3e43-11eb-8c1e-09f0d84f8a9a.png)

**Comment by badabing2005** [comment] 2020-12-15 00:46
**Resolved!**

Seeing both of you not having the issue, I dug into my customization files and found a domain level customization
```
---
switch:
  icon: mdi:light-switch
```
I must have been testing something at some point and probably forgot all about it.

Thanks
BB

**Comment by fwestenberg** [comment] 2020-12-15 12:13
Please update to v0.9 and let me know if it all works now with NVR. I will close this issue, please feel free to (re)open if something is wrong.

**Closed by fwestenberg** 2020-12-15 12:13 UTC
Labels: NVR, bug
