### ISSUE TITLE
Motion Detection

### ISSUE THREAD

**Issue by danbayliss** [fwestenberg/reolink_dev#90] opened 2020-12-10 00:08 UTC
**Describe the bug**
I've installed 0.8 via HACS and have the camera stream and switches working fine but the motion detection entity doesn't get updated when I walk in front of the camera. I can see the camera sees the motion as I have my own sensor that checks the follow URL every 2 seconds - http://192.168.0.8/api.cgi?cmd=GetMdState&user=user&password=password.

When I walk in front of my camera my picture-entity card and all switches become unavailable. I also get the following notification 'Login attempt or request with `invalid authentication from 192.168.0.2 (192.168.0.2) (Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:83.0) Gecko/20100101 Firefox/83.0)'`

**Logs**
`2020-12-10 00:02:58 ERROR (MainThread) [reolink.camera_api] Error translating Reolink settings response
2020-12-10 00:03:08 ERROR (MainThread) [reolink.camera_api] Error translating login response to json
2020-12-10 00:03:08 ERROR (MainThread) [reolink.camera_api] Error translating Reolink state response
2020-12-10 00:03:10 ERROR (stream_worker) [homeassistant.components.stream.worker] Error demuxing stream: [Errno 1414092869] Immediate exit requested: 'rtmp://192.168.0.8:1935/bcs/channel0_main.bcs?channel=0&stream=0&token=8f03fa1e3b880a0'
2020-12-10 00:03:17 ERROR (stream_worker) [homeassistant.components.stream.worker] Error demuxing stream: 
2020-12-10 00:03:18 ERROR (MainThread) [reolink.camera_api] Error translating login response to json
2020-12-10 00:03:18 ERROR (MainThread) [homeassistant.components.camera] Error requesting stream: camera.door does not support play stream service
2020-12-10 00:03:18 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 192.168.0.2 (192.168.0.2) (Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:83.0) Gecko/20100101 Firefox/83.0)
2020-12-10 00:03:50 ERROR (stream_worker) [homeassistant.components.stream.worker] Error opening stream rtmp://192.168.0.8:1935/bcs/channel0_main.bcs?channel=0&stream=0&token=8f03fa1e3b880a0
`

**To Reproduce**
Walk in front of camera

**Expected behavior**
Motion sensor should change from 'clear' to 'detected'

**Environment:**
Please provide useful information about your environment, like:
 - Home Assistant version: 0.118.5
 - Reolink camera model: RLC-420-5MP
 - Camera firmware number: v3.0.0.65_20071001

**Comment by fwestenberg** [comment] 2020-12-10 09:42
The switches and stream both rely on the token, so the camera should be logged in. For some reason, your camera couldn't get the data (timeout or token invalid) so it logged in again. 
Now the big question is: why did this fail? One thing I can think of, is there are no more sessions available for the camera. So your script in example also does a login. Also the Reolink app does. It probably ran out of sessions. Can you try to reboot the camera, wait for Home Assistant to reconnect and try again (without Reolink app and other scripts!).

**Comment by fwestenberg** [comment] 2020-12-10 09:43
By the way: I have the same camera and firmware running fine so it should be working!

**Comment by seymourddr** [comment] 2020-12-10 20:48
i have the same problem after updating to version 0.8. my RLC-410-5MP has the presence sensor that no longer works on HA but on reolink app or web browser it works correctly.

**Comment by fwestenberg** [comment] 2020-12-10 21:20
In version v0.7 it was polling the camera for every second, so sometimes it missed the motion in my case. So now we use a pash variant, the camera sends the events to Home Assistant. In your logfile should me a webhook URL right (with log set to debug). Is put this in your browser, do you see an incoming call in the HA log?

**Comment by dbiczo** [comment] 2020-12-10 22:00
I have the same problem with the camera motion sensor in Home Assistant. I tried rebooting the camera and removing and re-adding the integration. Push is enabled in the camera settings. I also get "Login attempt or request with invalid authentication" error when clicking on the preview video to get a live view in the lovelace camera card. Camera: RLC-520, Firmware: v3.0.0.116_20103112, Reolink_dev: 0.8. Many thanks for your efforts with the integration.

**Comment by rangulvers** [comment] 2020-12-11 13:39
I have the same issue with version 0.8. 

First thought that it might be the network issue as mentioned in another issue (https://github.com/fwestenberg/reolink_dev/issues/92)
For testing I hardwired all cameras so this is out of the question.

**Comment by rangulvers** [comment] 2020-12-11 13:50
2020-12-11 14:43:11 INFO (MainThread) [custom_components.reolink_dev.base] Host 192.168.xxx subscribed successfully to webhook https://192.168.xxx:8xxx/api/webhook/xxxxxxxxxxxxxxx
2020-12-11 14:45:24 DEBUG (MainThread) [custom_components.reolink_dev] Finished fetching reolink data in 5.257 seconds
2020-12-11 14:45:34 ERROR (MainThread) [reolink.camera_api] Error translating Reolink state response
2020-12-11 14:45:34 DEBUG (MainThread) [custom_components.reolink_dev] Finished fetching reolink data in 10.015 seconds
2020-12-11 14:46:34 ERROR (MainThread) [reolink.camera_api] Error translating Reolink settings response
2020-12-11 14:46:44 ERROR (MainThread) [reolink.camera_api] Error translating Reolink state response
2020-12-11 14:46:44 DEBUG (MainThread) [custom_components.reolink_dev] Finished fetching reolink data in 10.002 seconds
2020-12-11 14:46:44 ERROR (MainThread) [reolink.camera_api] Error translating login response to json
2020-12-11 14:46:44 ERROR (MainThread) [reolink.camera_api] Error translating Reolink state response
2020-12-11 14:46:44 DEBUG (MainThread) [custom_components.reolink_dev] Finished fetching reolink data in 20.849 seconds

**Comment by fwestenberg** [comment] 2020-12-11 15:04
The first line in the log means the webhook got created in HA and the camera subscribed to this. (When motion is detected, the camera calls the webhook). For some reason, the camera response from the API (not the subscription) is not OK. I have to say, 10+ seconds for fetching the data is not quite usual. The timeout of the API calls is set to 10 seconds. 
Can you also perform the actions described [here](https://github.com/fwestenberg/reolink_dev/issues/89#issuecomment-742373013) please?

**Comment by danbayliss** [comment] 2020-12-11 19:00
I've turned of all my camera access, rebooted HA and re-added this integration and my camera but it's still happening

**Here is my log file on boot up**
2020-12-11 18:46:47 INFO (MainThread) [homeassistant.setup] Setting up reolink_dev
2020-12-11 18:46:47 INFO (MainThread) [homeassistant.setup] Setup of domain reolink_dev took 0.0 seconds
2020-12-11 18:46:52 INFO (MainThread) [custom_components.reolink_dev.base] Host 192.168.0.8 subscribed successfully to webhook https://*.org/api/webhook/*****
2020-12-11 18:46:53 DEBUG (MainThread) [custom_components.reolink_dev] Finished fetching reolink data in 1.409 seconds
2020-12-11 18:46:53 INFO (MainThread) [homeassistant.components.camera] Setting up camera.reolink_dev
2020-12-11 18:46:53 INFO (MainThread) [homeassistant.components.switch] Setting up switch.reolink_dev
2020-12-11 18:46:53 INFO (MainThread) [homeassistant.components.binary_sensor] Setting up binary_sensor.reolink_dev
2020-12-11 18:46:57 INFO (MainThread) [homeassistant.components.stream] Started stream: rtmp://*:1935/bcs/channel0_main.bcs?channel=0&stream=0&token=*
2020-12-11 18:47:54 DEBUG (MainThread) [custom_components.reolink_dev] Finished fetching reolink data in 1.433 seconds
2020-12-11 18:48:55 DEBUG (MainThread) [custom_components.reolink_dev] Finished fetching reolink data in 1.455 seconds

**Here is what happens when I walk in front of the camera**
2020-12-11 18:54:05 ERROR (stream_worker) [homeassistant.components.stream.worker] Error demuxing stream: 
2020-12-11 18:54:09 ERROR (MainThread) [reolink.camera_api] Error translating Reolink settings response
2020-12-11 18:54:19 ERROR (MainThread) [reolink.camera_api] Error translating login response to json
2020-12-11 18:54:19 ERROR (MainThread) [reolink.camera_api] Error translating Reolink state response
2020-12-11 18:54:19 DEBUG (MainThread) [custom_components.reolink_dev] Finished fetching reolink data in 20.668 seconds
2020-12-11 18:54:25 INFO (MainThread) [homeassistant.components.websocket_api.http.connection] [139787427552224] Connection closed by client
2020-12-11 18:54:29 ERROR (MainThread) [reolink.camera_api] Error translating login response to json
2020-12-11 18:54:29 ERROR (MainThread) [homeassistant.components.camera] Error requesting stream: camera.door does not support play stream service
2020-12-11 18:54:29 ERROR (MainThread) [reolink.camera_api] Error translating login response to json
2020-12-11 18:54:29 ERROR (MainThread) [homeassistant.components.camera] Error requesting stream: camera.door does not support play stream service
2020-12-11 18:54:29 WARNING (MainThread) [homeassistant.components.http.ban] Login attempt or request with invalid authentication from 192.168.0.2 (192.168.0.2) (Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:83.0) Gecko/20100101 Firefox/83.0)

**And log file after**
2020-12-11 18:55:23 DEBUG (MainThread) [custom_components.reolink_dev] Finished fetching reolink data in 4.422 seconds
2020-12-11 18:56:24 DEBUG (MainThread) [custom_components.reolink_dev] Finished fetching reolink data in 1.412 seconds
2020-12-11 18:57:27 DEBUG (MainThread) [custom_components.reolink_dev] Finished fetching reolink data in 3.150 seconds

**Comment by fwestenberg** [comment] 2020-12-11 19:12
I just noticed you both use HTTPS, which should not be a problem of course. But it might be possible the Reolink camera does not respond well to that. The camera subscribes wellnin both cases, both have HTTPS and both crash on movement (when the camera calls the webhook). I will switch my test install to https asap to check this out.

**Comment by danbayliss** [comment] 2020-12-11 19:19
I use NGINX Home Assistant SSL proxy so i access HA using SSL externally and HTTP internally. 


I've just tried running Postman but not sure what i'm doing wrong. Attached is the output of the login. Is the token in the id field? If I paste that into the two token field I seem to get a failed response back
[token.json.txt](https://github.com/fwestenberg/reolink_dev/files/5681165/token.json.txt)
[Reolink API.postman_test_run.json.txt](https://github.com/fwestenberg/reolink_dev/files/5681166/Reolink.API.postman_test_run.json.txt)

**Comment by fwestenberg** [comment] 2020-12-11 19:25
Strange, the token should be in name:

```
"responseCode": {
				"code": 200,
				"name": "OK"
			},
```

But it just says OK??

**Comment by danbayliss** [comment] 2020-12-11 19:31
Yes it just says OK. I changed the default username from 'hass' to 'admin, added my password and changed the IP address in 'raw' and 'host'. I've never used postman before so not sure if i'm doing anything wrong!

**Comment by andersjohansson3** [comment] 2020-12-11 20:30
I've  had the same issues with not getting motion to trigger for 0.8, but the HTTPS question got me thinking. 
I'm also running a nginx reverse proxy and noticed the webhooks where getting registered with the external URL. Should be fine, my camera has access to outside world right now and everything, but it would not trigger motion at all. 
So I removed my external URL from the core config settings page, rebooted and saw that the camera registered with the internal HTTP webhook URL. And once it had done so, motion triggers just as expected.

When I added my external URL back in the config and rebooted I receive:
`2020-12-11 21:27:57 WARNING (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook d38b0bb74e22c7c7ce2087bb759304090a1fb8f38125fd494c8393f6d5591c3d from 192.168.XX.XX`
and motion once again has stopped working.

**Comment by fwestenberg** [comment] 2020-12-11 20:36
The reason you see this unregistered webhook error, is for some reason the unsubscribe is not working well at the moment. Not a big deal, because if the renew is not performed within 15 minutes, it gets unsubscribed anyway.

The HTTPS story I can confirm. I tried HTTPS also, and the webhook did not trigger. While on my installation with HTTP the motion event did work at the same time! So I will start searching for a solution to this...

**Comment by andersjohansson3** [comment] 2020-12-11 20:38
Would it be possible to force or give an option for the webhook registration to use the internal URL?

**Comment by fwestenberg** [comment] 2020-12-11 21:42
Can you reach your HA over HTTP?

**Comment by andersjohansson3** [comment] 2020-12-11 21:46
Not externally, I'm forcing it to https

**Comment by andersjohansson3** [comment] 2020-12-11 22:03
I guess you could skip using the async_generate_url and instead construct the url yourself through the get_url and async_generate_path?
`def async_generate_url(hass, webhook_id):
    """Generate the full URL for a webhook_id."""
    return "{}{}".format(
        get_url(hass, prefer_external=True, allow_cloud=False),
        async_generate_path(webhook_id),
    )`

**Comment by fwestenberg** [comment] 2020-12-11 22:29
I already tried this. But if your HA is not internal reachable by HTTP, it probably won't work. My not-working HA config used HTTPS internally and did not work.

**Comment by andersjohansson3** [comment] 2020-12-11 22:33
I'm using http internally, my nginx terminates ssl externally as well and forwards to http. So that part should work at least for me.
My config in /config/core is 

```
External URL: https://subdomain.domain.duckdns.org
Internal URL: http://localserver.lan:8123
```

**Comment by fwestenberg** [comment] 2020-12-12 10:07
Ok, thanks! I'll create a new version asap with: 

`get_url(hass, prefer_external=False`

Please be patient, I need to add some other things as well.

**Comment by andersjohansson3** [comment] 2020-12-13 18:02
I did a crude hack in my own `__init__.py` with the following additions / changes that seem to work. This allows me to get the internal (http) url:
After line 33
```
from homeassistant.helpers.network import get_url
```
From line 72
```
    webhook_id = await register_webhook(hass, base.event_id)
    #webhook_url = hass.components.webhook.async_generate_url(webhook_id)
    webhook_url = "{}{}".format(
      get_url(hass, prefer_external=False),
      hass.components.webhook.async_generate_path(webhook_id)
    )
```

**Comment by fwestenberg** [comment] 2020-12-14 13:46
Thanks, this was ecactly what I planned to change. I made a lot of fixes in [this](https://github.com/fwestenberg/reolink_dev/tree/NVR_and_bug_fixes) branch, you can download it as zip and overwrite all files in your custom_components/reolink_dev you can test it. Also the Options are fixed here, and I add the timeout setting. This one is not working yet, a fix in the python library is needed first. Please let me know the results. I know some small bugs are there:

- When adding the same camera again an error occurs
- Camera name for NVR gets the suffix _1 for stream 1 etc. This well be fixed later.

**Comment by rangulvers** [comment] 2020-12-14 16:25
Did some quick checks with the new Version

- The motion detection works as it should 
- The webhooks are created for the internal url 
 ```2020-12-14 17:17:59 INFO (MainThread) [custom_components.reolink_dev.base] Host 192.168.2.153 subscribed successfully to webhook http://192.168.xxx:8123/api/webhook/xxxxxxxxxxxxxxx
2020-12-14 17:17:59 INFO (MainThread) [custom_components.reolink_dev.base] Host 192.168.2.148 subscribed successfully to webhook http://192.168.xxxxx:8123/api/webhook/xxxxxxxxxx
```

Only drawback I saw : it created new entities for all reolink sensors and did not update the existing one. But this is not a big issue in my eyes

**Comment by fwestenberg** [comment] 2020-12-14 17:08
Thanks for testing. The new devices is because the unique id's are renamed. So first delete the integration should help.

**Comment by rangulvers** [comment] 2020-12-14 19:01
after more testing and really trying to get it to break ;) everything seems to be working fine. 

- [x] Motion detection

- [x] Webhook registration 

- [x] snapshot function

- [x] mobile notification after motion (with node red)

**Comment by andersjohansson3** [comment] 2020-12-14 19:43
Got to try it now also and I can only agree with the above comments. I deleted the integration before replacing the folder, after a reboot all added in nicely and everything works as expected for me. I have only tried it with one camera though.

**Comment by danbayliss** [comment] 2020-12-14 22:10
I've setup two cameras and both are working ok. Great work @fwestenberg!

**Comment by fwestenberg** [comment] 2020-12-14 22:20
Thanks and it's a pleasure to close this one. ;)

**Closed by fwestenberg** 2020-12-14 22:20 UTC
Labels: bug, question
