### ISSUE TITLE
Camera stream freeze at 02:00 (2 a.m.) nearly every night.

### ISSUE THREAD

**Issue by kolossboss** [fwestenberg/reolink_dev#62] opened 2020-08-23 08:53 UTC
Hi,
my realink camera stops/freezes at 02:00 (2a.m.) nearly every night. Nothing special happen at 02:00.
Only a google Drive backup is started.

```
- id: '1541223656718'
  alias: Snapshot Google Drive
  trigger:
  - at: 02:00:00
    platform: time
  condition: []
  action:
  - service: rest_command.google_backup
```

I got this error message in the log

`2020-08-23 02:00:26 ERROR (MainThread) [custom_components.reolink_dev.camera] Got exception while fetching the state: `

Looks like this:

![IMG_1092](https://user-images.githubusercontent.com/11015086/90974778-92100080-e52e-11ea-940a-e1fc78ee9845.jpg)

All other cams (not reolink) works fine. Only restart server fix this issue temporary. What can cause this? Please help.

**Comment by IvanPenyaHuguet** [comment] 2020-08-23 18:41
Probably it is the same as #60 , the cam is programmed with a reboot every Sunday at 2:00 am. Until it is fixed, I recommend to deactivate the reboot in cam configuration System > Reboot. It is not related with that, please give more information about how to reproduce it, maybe some information about the backup.

**Comment by kolossboss** [comment] 2020-08-23 19:48
Thanks for reply!
Sounds good. I will tried that! It feels like it is more often then once a week, but maybe I‘m wrong.

**Comment by IvanPenyaHuguet** [comment] 2020-08-24 13:28
Look if with the last release this is solved, if that is the case we clan close this.

**Closed** 2020-12-10 09:53 UTC

**Comment by Fietspomp86** [comment] 2021-03-17 11:39
Hi guys, I'm using this integration since a few days.
I own 2 Reolink cameras,  RLC-411WS and RLC-410W.

Both have this issue of showing a loop a few minutes.
Disabled the auto-reboot, but it happens every night it seems!
I'll try to get a debug log from the moment it happens.
