### ISSUE TITLE
Motion detection not working since upgrade

### ISSUE THREAD

**Issue by Lybbe77** [fwestenberg/reolink_dev#108] opened 2020-12-18 14:05 UTC
**Describe the bug**
I've upgrade from the configuration.yaml-integration to the fully HACS integration. But since the upgrade the binary sensors are no longer changing states on detection. I get a push from the Reolink app when motion is detected, but binary sensors are not changing state. 

No particular errors can be seen in the logs

Some settings such as stream type are also missing in OPTIONS

The setup worked flawless in prior reolink_dev version when used in configuration.yaml

**To Reproduce**
Upgraded to reolink_dev 0.9 through HACS
Removed reolink_dev and binary_sensors from configuration.yaml

Logs from startup:

`2020-12-18 13:42:32 INFO (MainThread) [homeassistant.setup] Setting up reolink_dev
2020-12-18 13:42:32 INFO (MainThread) [homeassistant.setup] Setup of domain reolink_dev took 0.0 seconds
2020-12-18 13:42:32 DEBUG (MainThread) [custom_components.reolink_dev.base] {'port': 80, 'host': '192.x.x.x’, 'username': ’user’, 'password': ’pass’, 'channel': 1}
2020-12-18 13:42:32 DEBUG (MainThread) [custom_components.reolink_dev.base] {}
2020-12-18 13:42:32 DEBUG (MainThread) [custom_components.reolink_dev.base] {'port': 80, 'host': '192.y.y.y’, 'username': ’user’, 'password': ’pass’, 'channel': 1}
2020-12-18 13:42:32 DEBUG (MainThread) [custom_components.reolink_dev.base] {}
2020-12-18 13:42:40 INFO (MainThread) [custom_components.reolink_dev.base] Host 192.x.x.x subscribed successfully to webhook https://192.x.x.x:8123/api/webhook/9db17eec865ef2f867b548d7693a36b166774ef54a29fa18331517e7d0a293dc!
2020-12-18 13:42:41 INFO (MainThread) [custom_components.reolink_dev.base] Host 192.y.y.y subscribed successfully to webhook https://192.y.y.y:8123/api/webhook/9122b2a5aad7009a862fa25d027af0750391881cd27ec194c803b79694ba62e6!
2020-12-18 13:42:41 DEBUG (MainThread) [custom_components.reolink_dev] Finished fetching reolink data in 0.439 seconds
2020-12-18 13:42:44 DEBUG (MainThread) [custom_components.reolink_dev] Finished fetching reolink data in 3.319 seconds
2020-12-18 13:42:44 INFO (MainThread) [homeassistant.components.camera] Setting up camera.reolink_dev
2020-12-18 13:42:44 INFO (MainThread) [homeassistant.components.switch] Setting up switch.reolink_dev
2020-12-18 13:42:44 INFO (MainThread) [homeassistant.components.binary_sensor] Setting up binary_sensor.reolink_dev
2020-12-18 13:42:44 INFO (MainThread) [homeassistant.components.camera] Setting up camera.reolink_dev
2020-12-18 13:42:44 INFO (MainThread) [homeassistant.components.switch] Setting up switch.reolink_dev
2020-12-18 13:42:44 INFO (MainThread) [homeassistant.components.binary_sensor] Setting up binary_sensor.reolink_dev
2020-12-18 13:43:44 DEBUG (MainThread) [custom_components.reolink_dev] Finished fetching reolink data in 0.306 seconds
2020-12-18 13:43:44 DEBUG (MainThread) [custom_components.reolink_dev] Finished fetching reolink data in 0.430 seconds
2020-12-18 13:44:44 DEBUG (MainThread) [custom_components.reolink_dev] Finished fetching reolink data in 0.269 seconds
2020-12-18 13:44:44 DEBUG (MainThread) [custom_components.reolink_dev] Finished fetching reolink data in 0.364 seconds
2020-12-18 13:45:44 DEBUG (MainThread) [custom_components.reolink_dev] Finished fetching reolink data in 0.250 seconds
2020-12-18 13:45:44 DEBUG (MainThread) [custom_components.reolink_dev] Finished fetching reolink data in 0.359 seconds
2020-12-18 13:46:44 DEBUG (MainThread) [custom_components.reolink_dev] Finished fetching reolink data in 0.237 seconds
2020-12-18 13:46:44 DEBUG (MainThread) [custom_components.reolink_dev] Finished fetching reolink data in 0.373 seconds`

**Expected behavior**
State change in binary sensors when motion is detected

**Screenshots**
Device info:
![device_info](https://user-images.githubusercontent.com/68653149/102622325-225afc80-4141-11eb-9167-e952af9d4c8e.png)

Options (with missing stream type):
![options](https://user-images.githubusercontent.com/68653149/102622379-39015380-4141-11eb-865e-44e3eb56ce4d.png)

Binary sensor:
![binary_sensor](https://user-images.githubusercontent.com/68653149/102622414-46b6d900-4141-11eb-8850-991c8681e460.png)

Motiondetection log with no events, but should be:
I changed the state manually just to test (can be seen below)
![camera](https://user-images.githubusercontent.com/68653149/102622498-677f2e80-4141-11eb-85cf-568396d5df6c.png)

**Environment:**
Homeassistant 0.118.5
Reolink_dev 0.9
2 pcs RLC-410-5MP
v3.0.0.136_20121100 (Also tried with a lower fw-version)

**Additional context**
Any idea why sensors are not updating as they should?

**Comment by andersjohansson3** [comment] 2020-12-18 21:22
I think it's most likely because you are using https internally. It seems like the reolink cameras does not like to trigger the webhooks on an https url like yours (https://192.x.x.x:8123/api/webhook/9db17eec865ef2f867b548d7693a36b166774ef54a29fa18331517e7d0a293dc!)
See the discussion in #90

**Comment by fwestenberg** [comment] 2020-12-18 21:27
That's right. I still don't see any solution to that. Also, what is the benefit of using https internally?

**Comment by andersjohansson3** [comment] 2020-12-18 21:33
@fwestenberg 
Is http hardcoded in the reolink api you are using [here](https://github.com/fwestenberg/reolink/blob/39b6eabda46114f2f43848140134b26b0f97066c/reolink/subscription_manager.py) ?
```
self._subscribe_url = f"http://{host}:{port}"

**Comment by Lybbe77** [comment] 2020-12-19 07:42
Interesting. Haven't thought about the internal_url. I updated the settings to use http and rebooted both HA and the cameras: 

2020-12-19 00:16:24 INFO (MainThread) [custom_components.reolink_dev.base] Host 192.168.x.x subscribed successfully to webhook **http://192.168.x.x:8123/api/webhook/b3700ffd8c7af148eb288355d22ee819a263b09c7a52c148c4863eaf5598cdf3!**

Unfortunately there's still no change of state in the binary_sensors on motion detection. Any other clues what may causing this?

**Comment by RikyUnreal** [comment] 2020-12-19 13:16
> That's right. I still don't see any solution to that.

Is it related to the same issue discussed in the NVR thread I suppose?

**Comment by Lybbe77** [comment] 2020-12-19 16:00
Update: I have no issues enabling or disabling, for example, IR-lights in HA by clicking the flashlight icon in the camera-image as can be seen from the log below:

`2020-12-19 15:47:21 DEBUG (MainThread) [reolink.camera_api] Sending command: SetIrLights to: 192.x.x.x with body: [{'cmd': 'SetIrLights', 'action': 0, 'param': {'IrLights': {'state': 'Auto'}}}]
2020-12-19 15:47:21 DEBUG (MainThread) [reolink.camera_api] Response from 192.x.x.x: [{'cmd': 'SetIrLights', 'code': 0, 'value': {'rspCode': 200}}]
2020-12-19 15:47:22 DEBUG (MainThread) [reolink.subscription_manager] Host 192.x.x.x should renew in: 462 seconds...
2020-12-19 15:47:22 DEBUG (MainThread) [custom_components.reolink_dev] Finished fetching reolink data in 0.202 seconds
2020-12-19 15:47:22 DEBUG (MainThread) [reolink.subscription_manager] Host 192.x.x.x should renew in: 462 seconds...`

Can't figure out why motion detection are not changing state of the binary_sensors though: I walk in front of the camera, Reolink-app push the notification to my phone, but nothing in the logs....

**Comment by fwestenberg** [comment] 2020-12-19 16:24
Pushing to your phone goes via the Google cloud (Android) or Apple cloud. This works completely separate/different from the solution we use for HA. First check out using Postman to POST some random body to your webhook. Check if HA receives this message...

**Comment by Lybbe77** [comment] 2020-12-19 16:47
Yes, i'm aware of that. What i mean is that the motion detection is correctly triggered by the cameras, but are not received or triggered in HA/reolink_dev for some reason.

I tried to post some random data to the webhook, and HA identifies the request but as an unregistered webhook. Could this be the issue? 

`2020-12-19 16:37:00 WARNING (MainThread) [homeassistant.components.webhook] Received message for unregistered webhook b3700ffd8c7af148eb288355d22ee819a263b09c7a52c148c4863eaf5598cdf3! from 50.16.249.180`

In either way motion by the camera should trigger a request to the webhook, but it doesn't...

**Comment by fwestenberg** [comment] 2020-12-19 17:45
The unregistered webhook error is not the problem here in the first place. Like you say the camera should trigger something at all. And for some reason it doesn't. What camera model do you use?

**Comment by Lybbe77** [comment] 2020-12-19 18:03
Thanks for clarifying. 

I have two RLC-410-5MP.

**Comment by fwestenberg** [comment] 2020-12-19 18:23
How strange! I use this cam also (wired) als motion detection works perfectly!

**Comment by Lybbe77** [comment] 2020-12-19 19:10
Yes, this is really strange. Wired cameras here as well. Is there anything else you can think of? I really don't want to downgrade to the older version that i had working (configuration.yaml-version)...

I'm also missing the stream setting in the OPTION menu as can be seen in the screenshot of the first post. Any idea why it's missing?

**Comment by fwestenberg** [comment] 2020-12-19 20:14
I can't think of anything else right now. But it has to be solved somehow! I removed the protocol setting, because I didn't see the use of it. RTMP has audio, and if streaming don't go well, you can lower the quality from the options menu.

**Comment by badabing2005** [comment] 2020-12-20 02:02
What could possibly cause the motion sensor entity to be unavailable whereas all other entities are working fine.
![image](https://user-images.githubusercontent.com/22603312/102703366-d8a30c80-423b-11eb-9994-b98805fbcfab.png)

And only on one camera
All other cameras have the entity properly detected, although not working correctly.
![image](https://user-images.githubusercontent.com/22603312/102703383-0d16c880-423c-11eb-9d7f-0517d5b6a4a1.png)

By the way my cameras are RLC-410 and RLC-420 connected to NVR.

See motion detection records of two different cameras
![image](https://user-images.githubusercontent.com/22603312/102703433-a2b25800-423c-11eb-8ad0-9533fb4a9b9e.png)
![image](https://user-images.githubusercontent.com/22603312/102703435-a6de7580-423c-11eb-8c5f-dbf079eaf169.png)

I think I have a better chance of hitting the lottery than the two having identical motion detection records, specially when each camera is pointed to totally different area (one indoors, and one outdoors)
And the triggers don't match any of the 8 cameras when comparing to the records in reolink app.

Maybe this is limited to NVRs like reported in the other thread.

**Comment by fwestenberg** [comment] 2020-12-20 06:07
This is because the motion detection at this moment doesn't have a filter for which NVR camera is the source. But since you DO have motion detection working in combination with NVR: can you enable logging in debug mode? We are looking for a XML with the tag: IsMotion.

**Comment by RikyUnreal** [comment] 2020-12-20 06:27
> This is because the motion detection at this moment doesn't have a filter for which NVR camera is the source. 

But in my previous configuration (0.7 and same NVR cameras added as a platform in configuration.yaml), I got the motion detection.
It could be useful?

**Comment by fwestenberg** [comment] 2020-12-20 06:34
No, I explained this here: https://github.com/fwestenberg/reolink_dev/issues/90#issuecomment-742806497

**Comment by Eddie46848** [comment] 2020-12-20 07:49
> I can't think of anything else right now. But it has to be solved somehow! I removed the protocol setting, because I didn't see the use of it. RTMP has audio, and if streaming don't go well, you can lower the quality from the options menu.

Hi
Sorry to jump in here. When changing the stream to sub, it still remains on main. 
So I cannot view my cameras anymore in home assistant because the bandwidth is too high?

**Comment by fwestenberg** [comment] 2020-12-20 08:47
@Eddie46848 please create a separate issue if needed. In the template are things like version etc, which I really need.

**Comment by Lybbe77** [comment] 2020-12-20 10:09
> I can't think of anything else right now. But it has to be solved somehow! I removed the protocol setting, because I didn't see the use of it. RTMP has audio, and if streaming don't go well, you can lower the quality from the options menu.

Removed the integration and the custom repository and looked through everything in HA to make sure no old entities were left in the system. 

Reinstalled reolink_dev and added the cameras again but still no go. 7 entities per camera are created as it should, but still no action when motion is detected.

Just to be sure: I have no SD-cards installed in the cameras. That shouldn't be a problem? Want to make sure that i haven't missed anything. It worked without SD-cards in the older version of reolink_dev, so shouldn't be an issue...

**Comment by badabing2005** [comment] 2020-12-20 13:46
Thanks @fwestenberg for the debug enabling hint.

I had to do this way
```
logger:
  default: warn
  logs:
    custom_components.reolink_dev: debug
    reolink: debug
```
Otherwise I would get all of HASS logging in debug (notice the addition of `default: warn`

Now that I have done it, Strangely I see no motion related xml entries
Perhaps it has more to do with http 400 that I'm getting (reported [here](https://github.com/fwestenberg/reolink_dev/issues/110))

Or is it a case of the logger not picking up everything?
Let me know how I can help

**Comment by Lybbe77** [comment] 2020-12-20 18:39
> Thanks @fwestenberg for the debug enabling hint.
> 
> I had to do this way
> 
> ```
> logger:
>   default: warn
>   logs:
>     custom_components.reolink_dev: debug
>     reolink: debug
> ```
> 
> Otherwise I would get all of HASS logging in debug (notice the addition of `default: warn`
> 
> Now that I have done it, Strangely I see no motion related xml entries
> Perhaps it has more to do with http 400 that I'm getting (reported [here](https://github.com/fwestenberg/reolink_dev/issues/110))
> 
> Or is it a case of the logger not picking up everything?
> Let me know how I can help

Thanks. I have the logger setup the same way. Searched for everything related to reolink and motion in the logs. In my case no errors whatsoever and subscription to the cameras are successful according to my logs, but still detection doesn't trigger.

**Comment by fwestenberg** [comment] 2020-12-20 18:50
Your logging is fine. This has to do with the 400 error indeed. I'll come back to this later.

**Comment by fwestenberg** [comment] 2020-12-21 11:26
Can you to remove all camera's and just add 1 to check if motion detection works? Maybe the problem is there are too many registrations on the same device (by all camera's).

**Comment by fwestenberg** [comment] 2020-12-21 16:30
Can you please update to v0.10 and let me know your experiences? Thanks!

**Comment by Lybbe77** [comment] 2020-12-21 17:01
> Can you please update to v0.10 and let me know your experiences? Thanks!

Upgraded to 1.0 through HACS. Unfortunately i experience the same issue as before. I've also tried by removing all (2) cameras and only add 1 camera, but no difference.

**Comment by badabing2005** [comment] 2020-12-21 17:07
Yeah me too,
Removed everything, even the HACS integration, and started fresh, added a single camera
Not seeing anything related to motion
With debug turned on this is what I see
No more http 400 :) but no motion detection either :(

```
2020-12-21 12:03:40 DEBUG (MainThread) [reolink.subscription_manager] Host 192.168.1.100 should renew in: 300 seconds...
2020-12-21 12:03:40 DEBUG (MainThread) [reolink.subscription_manager] Reolink host 192.168.1.100 got response status: 200. Payload: {<?xml version="1.0" encoding="UTF-8"?>
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://www.w3.org/2003/05/soap-envelope" xmlns:SOAP-ENC="http://www.w3.org/2003/05/soap-encoding" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:wsdd="http://schemas.xmlsoap.org/ws/2005/04/discovery" xmlns:wsa5="http://www.w3.org/2005/08/addressing" xmlns:xmime="http://tempuri.org/xmime.xsd" xmlns:xmime5="http://www.w3.org/2005/05/xmlmime" xmlns:xop="http://www.w3.org/2004/08/xop/include" xmlns:wsrfbf="http://docs.oasis-open.org/wsrf/bf-2" xmlns:tt="http://www.onvif.org/ver10/schema" xmlns:wstop="http://docs.oasis-open.org/wsn/t-1" xmlns:wsrfr="http://docs.oasis-open.org/wsrf/r-2" xmlns:ns1="http://www.onvif.org/ver10/actionengine/wsdl" xmlns:tev="http://www.onvif.org/ver10/events/wsdl" xmlns:ns10="http://www.onvif.org/ver10/events/wsdl/PullPointBinding" xmlns:ns11="http://www.onvif.org/ver10/events/wsdl/CreatePullPointBinding" xmlns:ns12="http://www.onvif.org/ver10/events/wsdl/PausableSubscriptionManagerBinding" xmlns:ns13="http://www.onvif.org/ver10/network/wsdl/RemoteDiscoveryBinding" xmlns:ns14="http://www.onvif.org/ver10/network/wsdl/DiscoveryLookupBinding" xmlns:tdn="http://www.onvif.org/ver10/network/wsdl" xmlns:ns3="http://www.onvif.org/ver20/analytics/wsdl/RuleEngineBinding" xmlns:ns4="http://www.onvif.org/ver20/analytics/wsdl/AnalyticsEngineBinding" xmlns:tan="http://www.onvif.org/ver20/analytics/wsdl" xmlns:ns5="http://www.onvif.org/ver10/events/wsdl/PullPointSubscriptionBinding" xmlns:ns6="http://www.onvif.org/ver10/events/wsdl/EventBinding" xmlns:ns7="http://www.onvif.org/ver10/events/wsdl/SubscriptionManagerBinding" xmlns:ns8="http://www.onvif.org/ver10/events/wsdl/NotificationProducerBinding" xmlns:wsnt="http://docs.oasis-open.org/wsn/b-2" xmlns:ns9="http://www.onvif.org/ver10/events/wsdl/NotificationConsumerBinding" xmlns:tad="http://www.onvif.org/ver10/analyticsdevice/wsdl" xmlns:tds="http://www.onvif.org/ver10/device/wsdl" xmlns:timg="http://www.onvif.org/ver20/imaging/wsdl" xmlns:tls="http://www.onvif.org/ver10/display/wsdl" xmlns:tmd="http://www.onvif.org/ver10/deviceIO/wsdl" xmlns:tptz="http://www.onvif.org/ver20/ptz/wsdl" xmlns:trc="http://www.onvif.org/ver10/recording/wsdl" xmlns:trp="http://www.onvif.org/ver10/replay/wsdl" xmlns:trt="http://www.onvif.org/ver10/media/wsdl" xmlns:trv="http://www.onvif.org/ver10/receiver/wsdl" xmlns:tse="http://www.onvif.org/ver10/search/wsdl" xmlns:ter="http://www.onvif.org/ver10/error" xmlns:tns1="http://www.onvif.org/ver10/topics" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"><SOAP-ENV:Header><wsa5:To SOAP-ENV:mustUnderstand="1">http://192.168.1.100:8000/onvif/Notification?Idx=00_0</wsa5:To><wsa5:Action SOAP-ENV:mustUnderstand="1">http://docs.oasis-open.org/wsn/bw-2/SubscriptionManager/RenewRequest</wsa5:Action></SOAP-ENV:Header><SOAP-ENV:Body><wsnt:RenewResponse><wsnt:TerminationTime>2020-12-21T17:07:02Z</wsnt:TerminationTime><wsnt:CurrentTime>2020-12-21T17:02:00Z</wsnt:CurrentTime></wsnt:RenewResponse></SOAP-ENV:Body></SOAP-ENV:Envelope>
}
2020-12-21 12:03:40 DEBUG (MainThread) [reolink.subscription_manager] Local time: 2020-12-21 17:03, camera time: 2020-12-21 17:02 (difference: -100.00206708908081), termination time: 2020-12-21 17:22
2020-12-21 12:03:40 DEBUG (MainThread) [custom_components.reolink_dev] Finished fetching reolink data in 0.310 seconds
```

**Comment by fwestenberg** [comment] 2020-12-21 20:18
Your logging shows the subscription manager got a connection, and the needed event is implemented (like expected). Can you try if the application Onvif Device Manager gets the events? Perhaps you can provide some details from there.

**Comment by badabing2005** [comment] 2020-12-21 22:39
Finally caught a motion related xml data
```
<SOAP-ENV:Envelope xmlns:SOAP-ENV="http://www.w3.org/2003/05/soap-envelope" xmlns:SOAP-ENC="http://www.w3.org/2003/05/soap-encoding" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:wsa="http://schemas.xmlsoap.org/ws/2004/08/addressing" xmlns:wsdd="http://schemas.xmlsoap.org/ws/2005/04/discovery" xmlns:wsa5="http://www.w3.org/2005/08/addressing" xmlns:xmime="http://tempuri.org/xmime.xsd" xmlns:xmime5="http://www.w3.org/2005/05/xmlmime" xmlns:xop="http://www.w3.org/2004/08/xop/include" xmlns:wsrfbf="http://docs.oasis-open.org/wsrf/bf-2" xmlns:tt="http://www.onvif.org/ver10/schema" xmlns:wstop="http://docs.oasis-open.org/wsn/t-1" xmlns:wsrfr="http://docs.oasis-open.org/wsrf/r-2" xmlns:ns1="http://www.onvif.org/ver10/actionengine/wsdl" xmlns:tev="http://www.onvif.org/ver10/events/wsdl" xmlns:ns10="http://www.onvif.org/ver10/events/wsdl/PullPointBinding" xmlns:ns11="http://www.onvif.org/ver10/events/wsdl/CreatePullPointBinding" xmlns:ns12="http://www.onvif.org/ver10/events/wsdl/PausableSubscriptionManagerBinding" xmlns:ns13="http://www.onvif.org/ver10/network/wsdl/RemoteDiscoveryBinding" xmlns:ns14="http://www.onvif.org/ver10/network/wsdl/DiscoveryLookupBinding" xmlns:tdn="http://www.onvif.org/ver10/network/wsdl" xmlns:ns3="http://www.onvif.org/ver20/analytics/wsdl/RuleEngineBinding" xmlns:ns4="http://www.onvif.org/ver20/analytics/wsdl/AnalyticsEngineBinding" xmlns:tan="http://www.onvif.org/ver20/analytics/wsdl" xmlns:ns5="http://www.onvif.org/ver10/events/wsdl/PullPointSubscriptionBinding" xmlns:ns6="http://www.onvif.org/ver10/events/wsdl/EventBinding" xmlns:ns7="http://www.onvif.org/ver10/events/wsdl/SubscriptionManagerBinding" xmlns:ns8="http://www.onvif.org/ver10/events/wsdl/NotificationProducerBinding" xmlns:wsnt="http://docs.oasis-open.org/wsn/b-2" xmlns:ns9="http://www.onvif.org/ver10/events/wsdl/NotificationConsumerBinding" xmlns:tad="http://www.onvif.org/ver10/analyticsdevice/wsdl" xmlns:tds="http://www.onvif.org/ver10/device/wsdl" xmlns:timg="http://www.onvif.org/ver20/imaging/wsdl" xmlns:tls="http://www.onvif.org/ver10/display/wsdl" xmlns:tmd="http://www.onvif.org/ver10/deviceIO/wsdl" xmlns:tptz="http://www.onvif.org/ver20/ptz/wsdl" xmlns:trc="http://www.onvif.org/ver10/recording/wsdl" xmlns:trp="http://www.onvif.org/ver10/replay/wsdl" xmlns:trt="http://www.onvif.org/ver10/media/wsdl" xmlns:trv="http://www.onvif.org/ver10/receiver/wsdl" xmlns:tse="http://www.onvif.org/ver10/search/wsdl" xmlns:ter="http://www.onvif.org/ver10/error" xmlns:tns1="http://www.onvif.org/ver10/topics" xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd" xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"><SOAP-ENV:Header><wsa5:Action SOAP-ENV:mustUnderstand="1">http://docs.oasis-open.org/wsn/bw-2/NotificationConsumer/Notify</wsa5:Action></SOAP-ENV:Header><SOAP-ENV:Body><wsnt:Notify><wsnt:NotificationMessage><wsnt:Topic Dialect="http://www.onvif.org/ver10/tev/topicExpression/ConcreteSet">tns1:RuleEngine/CellMotionDetector/Motion</wsnt:Topic><wsnt:Message><tt:Message UtcTime="2020-12-21T22:32:27Z" PropertyOperation="Changed"><tt:Source><tt:SimpleItem Name="VideoSourceConfigurationToken" Value="VideoSourceToken"/><tt:SimpleItem Name="VideoAnalyticsConfigurationToken" Value="VideoAnalyticsToken"/><tt:SimpleItem Name="Rule" Value="MyMotionDetectorRule"/></tt:Source><tt:Data><tt:SimpleItem Name="IsMotion" Value="true"/></tt:Data></tt:Message></wsnt:Message></wsnt:NotificationMessage></wsnt:Notify></SOAP-ENV:Body></SOAP-ENV:Envelope>
```

Hope this helps

**Comment by fwestenberg** [comment] 2020-12-21 23:21
And this one is from your NVR right? Did it trigger any binary sensor?

**Comment by badabing2005** [comment] 2020-12-22 00:11
Yes it is from NVR, there are some binary sensor triggers, but there is no real correlation between those and actual motion records in reolink app,

For example I just triggered a motion in front of one of the cameras, the reolink app recorded it, but nothing in HASS

**Comment by Lybbe77** [comment] 2020-12-22 07:03
I've never used OnVif device manager before, so not sure how to find/share XML-data as @badabing2005 did above.

Sharing a screenshot for where the camera detected motion. But still nothing in HA or any update of the binary sensors:

![Skärmavbild 2020-12-22 kl  07 59 09](https://user-images.githubusercontent.com/68653149/102859346-09499880-442c-11eb-92c8-967ef5ee438c.png)

**Comment by fwestenberg** [comment] 2020-12-22 09:13
This looks exactly the same as without NVR, I don't see any specification which stream actually triggered the motion. 
Can you please update the following 3 files from the custom components folder:
__init__.py
base.py 
binary_sensor.py

With the files from this branch?
https://github.com/fwestenberg/reolink_dev/tree/NVR-Webhook-subscription/custom_components/reolink_dev

I made sure only 1 subscription for the NVR will take place. If this works, I need to fix a couple of things to make sure everything works stable when removing camera's from HA etc. But first I need to know if this works. Please let me know.

**Comment by Lybbe77** [comment] 2020-12-22 09:31
> This looks exactly the same as without NVR, I don't see any specification which stream actually triggered the motion.
> Can you please update the following 3 files from the custom components folder:
> 
> ```
> __init__.py
> base.py 
> binary_sensor.py
> ```
> 
> With the files from this branch?
> https://github.com/fwestenberg/reolink_dev/tree/NVR-Webhook-subscription/custom_components/reolink_dev
> 
> I made sure only 1 subscription for the NVR will take place. If this works, I need to fix a couple of things to make sure everything works stable when removing camera's from HA etc. But first I need to know if this works. Please let me know.

Not sure if this was directed to me? Anyway. I've updated the 3 files above from the branch you referred to and restarted HA. No difference from the sensors or logs on motion detection.

**Comment by fwestenberg** [comment] 2020-12-22 09:43
@Lybbe77 do you use a NVR?

**Comment by Lybbe77** [comment] 2020-12-22 09:54
> @Lybbe77 do you use a NVR?

No. I use stand-alone cameras.

**Comment by fwestenberg** [comment] 2020-12-22 10:00
Ok, so your setup is just like mine. From the Onvif Device Mananger we see the events are triggered by the camera. From HA you switched internally from HTTPS to HTTP. Did you try to trigger the webhook (get it from the logging in debug mode) from Postman?

**Comment by Lybbe77** [comment] 2020-12-22 12:22
You might be into something here:

Triggering the webhook with the external adress (https://xxx.duckdns.org:8123) works with the "unregistered" message.
Triggering the webhook with the internal adress (http://192.x.x.x:8123) does NOT work. I get the following message:

Error: socket hang up

See screenshot below (Note that i have masked the IP in the screen after submission - not sent as 192.x.x.x) :)

![Skärmavbild 2020-12-22 kl  13 20 56](https://user-images.githubusercontent.com/68653149/102888183-8c80e380-4458-11eb-97fa-9cf2b5df1183.png)

Not sure if this is a Postman issue or something else, but internal_url is set to "http://192.x.x.x:8123". ExternaI_url set to the duckdns-domain for external access and ssl_key and ssl_certifications are set in config.

Any clue?

**Comment by fwestenberg** [comment] 2020-12-22 12:31
I'm almost certain this is the problem. The camera can't use HTTPS for some reason. And within your local network the HTTP call should work, or the camera also can't reach the webhook. Please try to fix this first, test with Postman and let me know!

**Comment by badabing2005** [comment] 2020-12-22 12:36
> This looks exactly the same as without NVR, I don't see any specification which stream actually triggered the motion.
> Can you please update the following 3 files from the custom components folder:
> 
> ```
> __init__.py
> base.py 
> binary_sensor.py
> ```
> 
> With the files from this branch?
> https://github.com/fwestenberg/reolink_dev/tree/NVR-Webhook-subscription/custom_components/reolink_dev
> 
> I made sure only 1 subscription for the NVR will take place. If this works, I need to fix a couple of things to make sure everything works stable when removing camera's from HA etc. But first I need to know if this works. Please let me know.

Unfortunately I woke up this morning and none of the cameras are working

All the entities are unavailable (all cameras)
![image](https://user-images.githubusercontent.com/22603312/102889213-3a27ce80-4428-11eb-85fd-e40d4e519427.png)
Hovering on that red refresh/exclamation mark shows restored.

and this is what I see in the logs from yesterday
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 236, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/reolink_dev/__init__.py", line 70, in async_setup_entry
    webhook_id = await register_webhook(hass, base.event_id)
  File "/config/custom_components/reolink_dev/__init__.py", line 155, in register_webhook
    handlers = hass.data["webhook"]
KeyError: 'webhook'
2020-12-21 20:39:20 DEBUG (MainThread) [reolink.camera_api] User admin has authorisation level admin
2020-12-21 20:39:20 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Tempo for reolink_dev
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 236, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/reolink_dev/__init__.py", line 70, in async_setup_entry
    webhook_id = await register_webhook(hass, base.event_id)
  File "/config/custom_components/reolink_dev/__init__.py", line 155, in register_webhook
    handlers = hass.data["webhook"]
KeyError: 'webhook'
2020-12-21 20:39:20 DEBUG (MainThread) [reolink.camera_api] User admin has authorisation level admin
2020-12-21 20:39:20 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Front Door for reolink_dev
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 236, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/reolink_dev/__init__.py", line 70, in async_setup_entry
    webhook_id = await register_webhook(hass, base.event_id)
  File "/config/custom_components/reolink_dev/__init__.py", line 155, in register_webhook
    handlers = hass.data["webhook"]
KeyError: 'webhook'
2020-12-21 20:39:20 DEBUG (MainThread) [reolink.camera_api] User admin has authorisation level admin
2020-12-21 20:39:20 ERROR (MainThread) [homeassistant.config_entries] Error setting up entry Driveway for reolink_dev
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 236, in async_setup
    result = await component.async_setup_entry(hass, self)  # type: ignore
  File "/config/custom_components/reolink_dev/__init__.py", line 70, in async_setup_entry
    webhook_id = await register_webhook(hass, base.event_id)
  File "/config/custom_components/reolink_dev/__init__.py", line 155, in register_webhook
    handlers = hass.data["webhook"]
KeyError: 'webhook'
```

Regardless I replaced the 3 files and restarted HASS
still none of the cameras are working

**Comment by Lybbe77** [comment] 2020-12-22 13:02
> I'm almost certain this is the problem. The camera can't use HTTPS for some reason. And within your local network the HTTP call should work, or the camera also can't reach the webhook. Please try to fix this first, test with Postman and let me know!

From what i could read when googling this, you can't have http working internally if SSL is enabled in HA. 
Are you using SSL and can still access HA through http internally?

**Comment by fwestenberg** [comment] 2020-12-22 13:11
I only use HA over HTTP and external with VPN, so no.

**Comment by fwestenberg** [comment] 2020-12-22 13:14
> > I'm almost certain this is the problem. The camera can't use HTTPS for some reason. And within your local network the HTTP call should work, or the camera also can't reach the webhook. Please try to fix this first, test with Postman and let me know!
> 
> From what i could read when googling this, you can't have http working internally if SSL is enabled in HA.
> Are you using SSL and can still access HA through http internally?

Perhaps you can contact @andersjohansson3, he reported something [here](https://github.com/fwestenberg/reolink_dev/issues/90#issuecomment-743462051) about HTTPS and HTTP.

**Comment by badabing2005** [comment] 2020-12-22 13:28
> From what i could read when googling this, you can't have http working internally if SSL is enabled in HA.
> Are you using SSL and can still access HA through http internally?

You can run HASS on http and setup a reverse proxy to serve HASS over https

HTTPS -> Reverse Proxy -> HTTP -> HASS

Take a look at `nginx proxy manager` addon

**Comment by Lybbe77** [comment] 2020-12-22 14:38
I will disable SSL just to confirm that this is the cause.

i run HA in docker (not Hassio) so i don't have the addons feature. Will look into nginx in docker as soon as this is sorted.

Thanks all 👍

**Comment by Lybbe77** [comment] 2020-12-22 14:57
Update: Motion detection and binary sensors confirmed working as soon as SSL on HA was disabled. 

I do think that many people are using SSL on their installations, so it might be an issue getting the reolink-integration working "out of the box" with SSL enabled.

When i have some spare time, i will setup nginx to make this work the way i want.

Thanks to all for help with troubleshooting 👍

**Comment by fwestenberg** [comment] 2020-12-22 15:05
Thanks, good to hear it works at least. I will try to fix this but is probably going to be a tough one. I will close this issue for now, and make a remark in the readme.

**Closed by fwestenberg** 2020-12-22 15:05 UTC

**Comment by badabing2005** [comment] 2020-12-22 19:20
@fwestenberg 

> Thanks, good to hear it works at least. I will try to fix this but is probably going to be a tough one. I will close this issue for now, and make a remark in the readme.

How about motion detection not working with NVR?

**Comment by badabing2005** [comment] 2020-12-22 19:23
Could it be that the SSL issue is due to self signed certificate which would fail unless `verify=False` is passed on `requests` ?
I haven't checked the code.

**Comment by fwestenberg** [comment] 2020-12-22 19:36
No, the request to the camera goes well. The problem is the camera can't connect to webhook via https. I don't know if there is a way to pass the certificate to the trusted certificate store of the camera...

**Comment by badabing2005** [comment] 2020-12-25 18:35
Maybe the Onvif Device Manager Certificates option can upload a certificate.

![image](https://user-images.githubusercontent.com/22603312/103140562-f8ac5300-46b5-11eb-9346-06d7a15fca4b.png)

**Comment by fwestenberg** [comment] 2020-12-25 19:25
I tried without success... I was also hoping this would workz because the onvif services have the certificate option indeed.

**Comment by badabing2005** [comment] 2020-12-25 23:25
> 
> 
> I tried without success... I was also hoping this would workz because the onvif services have the certificate option indeed.

:(
